p8105_HW2_yp2846
================

# Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
transit_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
           na =c("NA","."," "))|>
  janitor::clean_names() |>
  select(
    line, 
    station_name, 
    station_latitude, 
    station_longitude, 
    route1:route11, 
    entry, 
    vending, 
    entrance_type, 
    ada)|>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Warning: One or more parsing issues, call `problems()` on your data frame for details,
    ## e.g.:
    ##   dat <- vroom(...)
    ##   problems(dat)

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
dim(transit_df)
```

    ## [1] 1868   19

``` r
head(transit_df,10)
```

    ## # A tibble: 10 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      ""     ""    
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      ""     ""    
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      "R"    ""    
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      "R"    ""    
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      "R"    ""    
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      ""     ""    
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      ""     ""    
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      ""     ""    
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      ""     ""    
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      ""     ""    
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

The cleaned subway entrance dataset contains 1868 rows(observations) and
\`1919 columns(variables).

The variables include subway line and station name, station latitude and
longitude, routes served, whether entry is allowed, whether vending is
available, entrance type, and ADA compliance.

I cleaned the variable names using janitor::clean_names(), retained only
the variables relevant to the analysis and converted the entry variable
from “YES” and “NO” character values to a logical variable with TRUE and
FALSE.

The resulting dataset is not completely tidy because the routes served
are stored across multiple columns, from route1 through route11 rather
than in a single route variable.

``` r
transit_df |> 
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

``` r
transit_df |>
  filter(ada == TRUE)|>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

There are 84 ADA compliant stations.

``` r
transit_df |>
  filter(
    vending == "NO") |>
  summarize(
    transit_proportion = mean(entry)
  )
```

    ## # A tibble: 1 × 1
    ##   transit_proportion
    ##                <dbl>
    ## 1              0.377

The proportion of station entrances/exits without vending that allow
entrance is about 0.3770.

``` r
transit_long =
  transit_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name",
    values_drop_na = TRUE,
    values_transform = as.character
  )

transit_long |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

There are 60 distinct stations that serve the A train.

``` r
transit_long |>
  filter(
    route_name == "A",
    ada == TRUE
  ) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

Of the stations that serve the A train, 17 are ADA compliant.

# Problem 2

``` r
library(readxl)
```

``` r
# Read and clean the Mr. Trash Wheel sheet
trash_Mr_df =
  read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  )|>
  janitor::clean_names()|>
  filter(!is.na(dumpster))|>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.integer(year),
    trash_wheel = "Mr."
  )
# head(trash_Mr_df, 5)
# tail(trash_Mr_df, 5)
dim(trash_Mr_df)
```

    ## [1] 740  15

``` r
# Read and clean the Professor Trash Wheel sheet
trash_professor_df =
  read_excel(
    "./data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139"
  )|>
  janitor::clean_names()|>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
# Treat the non-numeric entry "dive" in plastic_bottles as missing
    plastic_bottles = na_if(plastic_bottles, "dive"),
    plastic_bottles = as.double(plastic_bottles),
    trash_wheel = "Professor"
  )

# unique(trash_professor_df$plastic_bottles)
# trash_professor_df |>
#   filter(plastic_bottles == "dive") |>
#   select(everything())
# head(trash_professor_df, 5)
# tail(trash_professor_df, 5)
dim(trash_professor_df)
```

    ## [1] 137  14

``` r
# Read and clean the Gwynnda the Good Wheel of the W sheet
trash_Gwynnda_df =
  read_excel("./data/202610 Trash Wheel Collection Data.xlsx",
             sheet = "Gwynnda the Good Wheel of the W",
             range = "A2:L394")|>
  janitor::clean_names()|>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Gwynnda"
  )
# head(trash_Gwynns_df, 5)
# tail(trash_Gwynns_df, 5)
dim(trash_Gwynnda_df)
```

    ## [1] 392  13

``` r
trash_combine = 
  bind_rows(
    trash_Mr_df,
    trash_professor_df,
    trash_Gwynnda_df
  )
# head(trash_combine,5)
# tail(trash_combine,5)
# dim(trash_combine)
```

There are 1269 rows and 15 columns in resulting dataset. It combines
data from Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda.

Key variables include dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered,
trash_wheel.

The total weight of trash collected by Professor Trash Wheel is 294.96.

The total number of cigarette butts collected by Gwynnda in June of 2022
is 18120.

# Problem 3

``` r
baseline_df =
  read_csv("./data/data_mci/MCI_baseline.csv",
                        skip = 1,
                        na = c("NA"," ","."))|>
  janitor::clean_names()|>
  mutate(
    sex = recode(
      sex,
      '0' = "Female",
      '1' = "Male"
    ),
    apoe4 = recode(
      apoe4,
      '0' = "APOE4 non-carrier",
      '1' = "APOE4 carrier"
    )
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(baseline_df,5)
```

    ## # A tibble: 5 × 6
    ##      id current_age sex    education apoe4             age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>                    <dbl>
    ## 1     1        63.1 Female        16 APOE4 carrier             NA  
    ## 2     2        65.6 Female        20 APOE4 carrier             NA  
    ## 3     3        62.5 Male          16 APOE4 carrier             66.8
    ## 4     4        69.8 Female        16 APOE4 non-carrier         NA  
    ## 5     5        66   Male          16 APOE4 non-carrier         68.7

``` r
tail(baseline_df,5)
```

    ## # A tibble: 5 × 6
    ##      id current_age sex    education apoe4             age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>                    <dbl>
    ## 1   479        68.6 Female        18 APOE4 non-carrier           NA
    ## 2   480        64.9 Female        20 APOE4 non-carrier           NA
    ## 3   481        63.9 Male          16 APOE4 non-carrier           NA
    ## 4   482        61.6 Male          18 APOE4 non-carrier           NA
    ## 5   483        63.4 Male          16 APOE4 carrier               NA

``` r
baseline_df = baseline_df |>
  filter(is.na(age_at_onset)| age_at_onset > current_age)
baseline_df
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4             age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>                    <dbl>
    ##  1     1        63.1 Female        16 APOE4 carrier             NA  
    ##  2     2        65.6 Female        20 APOE4 carrier             NA  
    ##  3     3        62.5 Male          16 APOE4 carrier             66.8
    ##  4     4        69.8 Female        16 APOE4 non-carrier         NA  
    ##  5     5        66   Male          16 APOE4 non-carrier         68.7
    ##  6     6        62.5 Male          16 APOE4 non-carrier         NA  
    ##  7     7        66.5 Male          18 APOE4 non-carrier         74  
    ##  8     8        67.2 Female        18 APOE4 non-carrier         NA  
    ##  9     9        66.7 Female        16 APOE4 non-carrier         NA  
    ## 10    10        64.1 Female        18 APOE4 non-carrier         NA  
    ## # ℹ 469 more rows

``` r
baseline_df |>
  summarize(
    n_participants = n(),
    n_mci = sum(!is.na(age_at_onset)),
    mean_age = mean(current_age),
    proportion_female_apoe4 = sum(sex=="Female" & apoe4 == "APOE4 carrier")/sum(sex=="Female") 
  )
```

    ## # A tibble: 1 × 4
    ##   n_participants n_mci mean_age proportion_female_apoe4
    ##            <int> <int>    <dbl>                   <dbl>
    ## 1            479    93     65.0                     0.3

The baseline demographic dataset required some cleaning during import
because the first row of the original CSV contained variable
descriptions rather than variable names. I therefore skipped the first
row when importing the data and treated “.” as a missing value during
import.

The variables include id, current_age, sex, education, apoe4,
age_at_onset.

I cleaned the variable names using janitor::clean_names() and recoded
the sex and APOE4 variables into descriptive categorical variables. I
converted the sex variable from numeric values “0” and “1” to a
character variable with levels “Female” and “Male”. I also converted the
apoe4 variable from numeric values “0” and “1” to a character variable
with levels “APOE4 non-carrier” and “APOE4 carrier”.

Participants whose age at MCI onset was less than or equal to their age
at study baseline were removed because they did not satisfy the
inclusion criterion of being free of MCI at baseline. Four participants
were excluded for this reason.

After applying the inclusion criterion, the baseline dataset contains
479 participants. Of these, 93 developed MCI during follow-up. The
average age at study baseline was approximately 65.03 years. Among women
in the study, 30% were APOE4 carriers.

``` r
amyloid_df =
  read_csv("./data/data_mci/mci_amyloid.csv",
           skip = 1,
           na = c("NA","Na","."," "))|>
  janitor::clean_names()|>
   pivot_longer(
      baseline:time_8,
      names_to = "time",
      values_to = "amyloid"
   )|>
   mutate(
    time = case_match(
      time,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8
   )
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# head(amyloid_df,5)
# tail(amyloid_df,5)
```

The amyloid dataset was originally stored in wide format, with separate
columns for measurements at baseline and years 2, 4, 6, and 8. I
reshaped the data into long format so that each row represents one
participant at one measurement time. I also recoded the time variable as
numeric years since baseline. The resulting dataset contains repeated
longitudinal amyloid measurements for each participant, so participants
may contribute up to five observations over the follow-up period.

``` r
baseline_df |>
  anti_join(
    amyloid_df,
    by = c("id" = "study_id")
  )
```

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4             age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>                    <dbl>
    ## 1    14        58.4 Female        20 APOE4 non-carrier         66.2
    ## 2    49        64.7 Male          16 APOE4 non-carrier         68.4
    ## 3    92        68.6 Female        20 APOE4 non-carrier         NA  
    ## 4   179        68.1 Male          16 APOE4 non-carrier         NA  
    ## 5   268        61.4 Female        18 APOE4 carrier             67.5
    ## 6   304        63.8 Female        16 APOE4 non-carrier         NA  
    ## 7   389        59.3 Female        16 APOE4 non-carrier         NA  
    ## 8   412        67   Male          16 APOE4 carrier             NA

There are 8 participants who appear in the cleaned baseline dataset but
not in the amyloid dataset.

``` r
amyloid_df |>
  distinct(study_id) |>
  anti_join(
    baseline_df,
    by = c("study_id" = "id")
  )
```

    ## # A tibble: 16 × 1
    ##    study_id
    ##       <dbl>
    ##  1       72
    ##  2      234
    ##  3      283
    ##  4      380
    ##  5      484
    ##  6      485
    ##  7      486
    ##  8      487
    ##  9      488
    ## 10      489
    ## 11      490
    ## 12      491
    ## 13      492
    ## 14      493
    ## 15      494
    ## 16      495

There are 16 participants appear in the amyloid dataset but not in the
cleaned baseline dataset.

This indicates that the two datasets do not contain exactly the same set
of participants, so an inner join is appropriate for creating a dataset
restricted to participants observed in both datasets.

``` r
combined_df =
  baseline_df |>
  inner_join(
    amyloid_df,
    by = c("id" = "study_id")
  )

combined_df |>
  summarize(
    n_rows = n(),
    n_participants = n_distinct(id)
  )
```

    ## # A tibble: 1 × 2
    ##   n_rows n_participants
    ##    <int>          <int>
    ## 1   2355            471

The combined dataset contains 2355 observations from 471 unique
participants who appear in both the cleaned baseline and amyloid
datasets. Because the amyloid data are longitudinal, each participant
may contribute multiple rows corresponding to different measurement
times. The combined dataset includes baseline demographic
characteristics, MCI-related information, APOE4 carrier status,
measurement time, and amyloid biomarker values.

``` r
write_csv(
  combined_df,
  "./data/data_mci/mci_complete.csv"
)
```
